language: php
php:
  - nightly
  - 7.2
  - 7.1
matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer selfupdate
  - COMPOSER_ROOT_VERSION=dev-master composer update --no-interaction --prefer-dist
  - COMPOSER_ROOT_VERSION=dev-master composer require codeclimate/php-test-reporter:dev-master --dev

script:
  - ./vendor/phpunit/phpunit/phpunit -v --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN= ./vendor/bin/test-reporter
